apiVersion: v1
kind: Service
metadata:
  name: smartenergy-service
spec:
  selector:
    app: backend   # FIXED LABEL
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
